import { FormLabel } from '@mui/material';
import { useEffect, useState } from 'react';
import { useFormContext } from 'react-hook-form';
import { useDispatch, useSelector } from 'react-redux';
import { selectorCountries, useCountriesSlice } from '~/common/slices/parametrics/geo/country.redux';
import { useI18n } from '~/common/utils';
import { ComponentGeneratorParams } from '../DynamicControl';
import { DynamicFieldData } from '../dynamic-control-types';
import { createSelect } from './Select';

export enum CitySelectionLevel {
  CONTINENT = 6,
  COUNTRY = 5,
  STATE = 4,
  CITY = 3,
  DISTRICT = 2,
  BOROUGH = 1,
}

export interface CitySelectorParams extends ComponentGeneratorParams {
  highSelectionLevel?: CitySelectionLevel;
  minimumSelectionLevel?: CitySelectionLevel;
}

// interface CountryInfo {label:string, value:string, states:{label:string, value:string, cities:{label:string, value:string, districts?:{label?:string, value?:string}[]}[]}[]}

const countries: any = [
  {
    label: 'Colombia',
    value: 'CO',
    states: [
      {
        label: 'Antioquia',
        value: '05',
        cities: [
          { label: 'Medellín', value: '05001' },
          { label: 'Abejorral', value: '05002' },
          { label: 'Abriaquí', value: '05004' },
          { label: 'Alejandría', value: '05021' },
          { label: 'Amagá', value: '05030' },
          { label: 'Amalfi', value: '05031' },
          { label: 'Andes', value: '05034' },
          { label: 'Angelópolis', value: '05036' },
          { label: 'Angostura', value: '05038' },
          { label: 'Anorí', value: '05040' },
          { label: 'Santa Fé De Antioquia', value: '05042' },
          { label: 'Anzá', value: '05044' },
          { label: 'Apartadó', value: '05045' },
          { label: 'Arboletes', value: '05051' },
          { label: 'Argelia', value: '05055' },
          { label: 'Armenia', value: '05059' },
          { label: 'Barbosa', value: '05079' },
          { label: 'Belmira', value: '05086' },
          { label: 'Bello', value: '05088' },
          { label: 'Betania', value: '05091' },
          { label: 'Betulia', value: '05093' },
          { label: 'Ciudad Bolívar', value: '05101' },
          { label: 'Briceño', value: '05107' },
          { label: 'Buriticá', value: '05113' },
          { label: 'Cáceres', value: '05120' },
          { label: 'Caicedo', value: '05125' },
          { label: 'Caldas', value: '05129' },
          { label: 'Campamento', value: '05134' },
          { label: 'Cañasgordas', value: '05138' },
          { label: 'Caracolí', value: '05142' },
          { label: 'Caramanta', value: '05145' },
          { label: 'Carepa', value: '05147' },
          { label: 'El Carmen De Viboral', value: '05148' },
          { label: 'Carolina', value: '05150' },
          { label: 'Caucasia', value: '05154' },
          { label: 'Chigorodó', value: '05172' },
          { label: 'Cisneros', value: '05190' },
          { label: 'Cocorná', value: '05197' },
          { label: 'Concepción', value: '05206' },
          { label: 'Concordia', value: '05209' },
          { label: 'Copacabana', value: '05212' },
          { label: 'Dabeiba', value: '05234' },
          { label: 'Donmatías', value: '05237' },
          { label: 'Ebéjico', value: '05240' },
          { label: 'El Bagre', value: '05250' },
          { label: 'Entrerríos', value: '05264' },
          { label: 'Envigado', value: '05266' },
          { label: 'Fredonia', value: '05282' },
          { label: 'Frontino', value: '05284' },
          { label: 'Giraldo', value: '05306' },
          { label: 'Girardota', value: '05308' },
          { label: 'Gómez Plata', value: '05310' },
          { label: 'Granada', value: '05313' },
          { label: 'Guadalupe', value: '05315' },
          { label: 'Guarne', value: '05318' },
          { label: 'Guatapé', value: '05321' },
          { label: 'Heliconia', value: '05347' },
          { label: 'Hispania', value: '05353' },
          { label: 'Itagüí', value: '05360' },
          { label: 'Ituango', value: '05361' },
          { label: 'Jardín', value: '05364' },
          { label: 'Jericó', value: '05368' },
          { label: 'La Ceja', value: '05376' },
          { label: 'La Estrella', value: '05380' },
          { label: 'La Pintada', value: '05390' },
          { label: 'La Unión', value: '05400' },
          { label: 'Liborina', value: '05411' },
          { label: 'Maceo', value: '05425' },
          { label: 'Marinilla', value: '05440' },
          { label: 'Montebello', value: '05467' },
          { label: 'Murindó', value: '05475' },
          { label: 'Mutatá', value: '05480' },
          { label: 'Nariño', value: '05483' },
          { label: 'Necoclí', value: '05490' },
          { label: 'Nechí', value: '05495' },
          { label: 'Olaya', value: '05501' },
          { label: 'Peñol', value: '05541' },
          { label: 'Peque', value: '05543' },
          { label: 'Pueblorrico', value: '05576' },
          { label: 'Puerto Berrío', value: '05579' },
          { label: 'Puerto Nare', value: '05585' },
          { label: 'Puerto Triunfo', value: '05591' },
          { label: 'Remedios', value: '05604' },
          { label: 'Retiro', value: '05607' },
          { label: 'Rionegro', value: '05615' },
          { label: 'Sabanalarga', value: '05628' },
          { label: 'Sabaneta', value: '05631' },
          { label: 'Salgar', value: '05642' },
          { label: 'San Andrés De Cuerquía', value: '05647' },
          { label: 'San Carlos', value: '05649' },
          { label: 'San Francisco', value: '05652' },
          { label: 'San Jerónimo', value: '05656' },
          { label: 'San José De La Montaña', value: '05658' },
          { label: 'San Juan De Urabá', value: '05659' },
          { label: 'San Luis', value: '05660' },
          { label: 'San Pedro De Los Milagros', value: '05664' },
          { label: 'San Pedro De Urabá', value: '05665' },
          { label: 'San Rafael', value: '05667' },
          { label: 'San Roque', value: '05670' },
          { label: 'San Vicente Ferrer', value: '05674' },
          { label: 'Santa Bárbara', value: '05679' },
          { label: 'Santa Rosa De Osos', value: '05686' },
          { label: 'Santo Domingo', value: '05690' },
          { label: 'El Santuario', value: '05697' },
          { label: 'Segovia', value: '05736' },
          { label: 'Sonsón', value: '05756' },
          { label: 'Sopetrán', value: '05761' },
          { label: 'Támesis', value: '05789' },
          { label: 'Tarazá', value: '05790' },
          { label: 'Tarso', value: '05792' },
          { label: 'Titiribí', value: '05809' },
          { label: 'Toledo', value: '05819' },
          { label: 'Turbo', value: '05837' },
          { label: 'Uramita', value: '05842' },
          { label: 'Urrao', value: '05847' },
          { label: 'Valdivia', value: '05854' },
          { label: 'Valparaíso', value: '05856' },
          { label: 'Vegachí', value: '05858' },
          { label: 'Venecia', value: '05861' },
          { label: 'Vigía Del Fuerte', value: '05873' },
          { label: 'Yalí', value: '05885' },
          { label: 'Yarumal', value: '05887' },
          { label: 'Yolombó', value: '05890' },
          { label: 'Yondó', value: '05893' },
          { label: 'Zaragoza', value: '05895' },
        ],
      },
      {
        label: 'Atlántico',
        value: '08',
        cities: [
          { label: 'Barranquilla', value: '08001' },
          { label: 'Baranoa', value: '08078' },
          { label: 'Campo De La Cruz', value: '08137' },
          { label: 'Candelaria', value: '08141' },
          { label: 'Galapa', value: '08296' },
          { label: 'Juan De Acosta', value: '08372' },
          { label: 'Luruaco', value: '08421' },
          { label: 'Malambo', value: '08433' },
          { label: 'Manatí', value: '08436' },
          { label: 'Palmar De Varela', value: '08520' },
          { label: 'Piojó', value: '08549' },
          { label: 'Polonuevo', value: '08558' },
          { label: 'Ponedera', value: '08560' },
          { label: 'Puerto Colombia', value: '08573' },
          { label: 'Repelón', value: '08606' },
          { label: 'Sabanagrande', value: '08634' },
          { label: 'Sabanalarga', value: '08638' },
          { label: 'Santa Lucía', value: '08675' },
          { label: 'Santo Tomás', value: '08685' },
          { label: 'Soledad', value: '08758' },
          { label: 'Suan', value: '08770' },
          { label: 'Tubará', value: '08832' },
          { label: 'Usiacurí', value: '08849' },
        ],
      },
      { label: 'Bogotá, D.C.', value: '11', cities: [{ label: 'Bogotá, D.C.', value: '11001' }] },
      {
        label: 'Bolívar',
        value: '13',
        cities: [
          { label: 'Cartagena De Indias', value: '13001' },
          { label: 'Achí', value: '13006' },
          { label: 'Altos Del Rosario', value: '13030' },
          { label: 'Arenal', value: '13042' },
          { label: 'Arjona', value: '13052' },
          { label: 'Arroyohondo', value: '13062' },
          { label: 'Barranco De Loba', value: '13074' },
          { label: 'Calamar', value: '13140' },
          { label: 'Cantagallo', value: '13160' },
          { label: 'Cicuco', value: '13188' },
          { label: 'Córdoba', value: '13212' },
          { label: 'Clemencia', value: '13222' },
          { label: 'El Carmen De Bolívar', value: '13244' },
          { label: 'El Guamo', value: '13248' },
          { label: 'El Peñón', value: '13268' },
          { label: 'Hatillo De Loba', value: '13300' },
          { label: 'Magangué', value: '13430' },
          { label: 'Mahates', value: '13433' },
          { label: 'Margarita', value: '13440' },
          { label: 'María La Baja', value: '13442' },
          { label: 'Montecristo', value: '13458' },
          { label: 'Santa Cruz De Mompox', value: '13468' },
          { label: 'Morales', value: '13473' },
          { label: 'Norosí', value: '13490' },
          { label: 'Pinillos', value: '13549' },
          { label: 'Regidor', value: '13580' },
          { label: 'Río Viejo', value: '13600' },
          { label: 'San Cristóbal', value: '13620' },
          { label: 'San Estanislao', value: '13647' },
          { label: 'San Fernando', value: '13650' },
          { label: 'San Jacinto', value: '13654' },
          { label: 'San Jacinto Del Cauca', value: '13655' },
          { label: 'San Juan Nepomuceno', value: '13657' },
          { label: 'San Martín De Loba', value: '13667' },
          { label: 'San Pablo', value: '13670' },
          { label: 'Santa Catalina', value: '13673' },
          { label: 'Santa Rosa', value: '13683' },
          { label: 'Santa Rosa Del Sur', value: '13688' },
          { label: 'Simití', value: '13744' },
          { label: 'Soplaviento', value: '13760' },
          { label: 'Talaigua Nuevo', value: '13780' },
          { label: 'Tiquisio', value: '13810' },
          { label: 'Turbaco', value: '13836' },
          { label: 'Turbaná', value: '13838' },
          { label: 'Villanueva', value: '13873' },
          { label: 'Zambrano', value: '13894' },
        ],
      },
      {
        label: 'Boyacá',
        value: '15',
        cities: [
          { label: 'Tunja', value: '15001' },
          { label: 'Almeida', value: '15022' },
          { label: 'Aquitania', value: '15047' },
          { label: 'Arcabuco', value: '15051' },
          { label: 'Belén', value: '15087' },
          { label: 'Berbeo', value: '15090' },
          { label: 'Betéitiva', value: '15092' },
          { label: 'Boavita', value: '15097' },
          { label: 'Boyacá', value: '15104' },
          { label: 'Briceño', value: '15106' },
          { label: 'Buenavista', value: '15109' },
          { label: 'Busbanzá', value: '15114' },
          { label: 'Caldas', value: '15131' },
          { label: 'Campohermoso', value: '15135' },
          { label: 'Cerinza', value: '15162' },
          { label: 'Chinavita', value: '15172' },
          { label: 'Chiquinquirá', value: '15176' },
          { label: 'Chiscas', value: '15180' },
          { label: 'Chita', value: '15183' },
          { label: 'Chitaraque', value: '15185' },
          { label: 'Chivatá', value: '15187' },
          { label: 'Ciénega', value: '15189' },
          { label: 'Cómbita', value: '15204' },
          { label: 'Coper', value: '15212' },
          { label: 'Corrales', value: '15215' },
          { label: 'Covarachía', value: '15218' },
          { label: 'Cubará', value: '15223' },
          { label: 'Cucaita', value: '15224' },
          { label: 'Cuítiva', value: '15226' },
          { label: 'Chíquiza', value: '15232' },
          { label: 'Chivor', value: '15236' },
          { label: 'Duitama', value: '15238' },
          { label: 'El Cocuy', value: '15244' },
          { label: 'El Espino', value: '15248' },
          { label: 'Firavitoba', value: '15272' },
          { label: 'Floresta', value: '15276' },
          { label: 'Gachantivá', value: '15293' },
          { label: 'Gámeza', value: '15296' },
          { label: 'Garagoa', value: '15299' },
          { label: 'Guacamayas', value: '15317' },
          { label: 'Guateque', value: '15322' },
          { label: 'Guayatá', value: '15325' },
          { label: 'Güicán De La Sierra', value: '15332' },
          { label: 'Iza', value: '15362' },
          { label: 'Jenesano', value: '15367' },
          { label: 'Jericó', value: '15368' },
          { label: 'Labranzagrande', value: '15377' },
          { label: 'La Capilla', value: '15380' },
          { label: 'La Victoria', value: '15401' },
          { label: 'La Uvita', value: '15403' },
          { label: 'Villa De Leyva', value: '15407' },
          { label: 'Macanal', value: '15425' },
          { label: 'Maripí', value: '15442' },
          { label: 'Miraflores', value: '15455' },
          { label: 'Mongua', value: '15464' },
          { label: 'Monguí', value: '15466' },
          { label: 'Moniquirá', value: '15469' },
          { label: 'Motavita', value: '15476' },
          { label: 'Muzo', value: '15480' },
          { label: 'Nobsa', value: '15491' },
          { label: 'Nuevo Colón', value: '15494' },
          { label: 'Oicatá', value: '15500' },
          { label: 'Otanche', value: '15507' },
          { label: 'Pachavita', value: '15511' },
          { label: 'Páez', value: '15514' },
          { label: 'Paipa', value: '15516' },
          { label: 'Pajarito', value: '15518' },
          { label: 'Panqueba', value: '15522' },
          { label: 'Pauna', value: '15531' },
          { label: 'Paya', value: '15533' },
          { label: 'Paz De Río', value: '15537' },
          { label: 'Pesca', value: '15542' },
          { label: 'Pisba', value: '15550' },
          { label: 'Puerto Boyacá', value: '15572' },
          { label: 'Quípama', value: '15580' },
          { label: 'Ramiriquí', value: '15599' },
          { label: 'Ráquira', value: '15600' },
          { label: 'Rondón', value: '15621' },
          { label: 'Saboyá', value: '15632' },
          { label: 'Sáchica', value: '15638' },
          { label: 'Samacá', value: '15646' },
          { label: 'San Eduardo', value: '15660' },
          { label: 'San José De Pare', value: '15664' },
          { label: 'San Luis De Gaceno', value: '15667' },
          { label: 'San Mateo', value: '15673' },
          { label: 'San Miguel De Sema', value: '15676' },
          { label: 'San Pablo De Borbur', value: '15681' },
          { label: 'Santana', value: '15686' },
          { label: 'Santa María', value: '15690' },
          { label: 'Santa Rosa De Viterbo', value: '15693' },
          { label: 'Santa Sofía', value: '15696' },
          { label: 'Sativanorte', value: '15720' },
          { label: 'Sativasur', value: '15723' },
          { label: 'Siachoque', value: '15740' },
          { label: 'Soatá', value: '15753' },
          { label: 'Socotá', value: '15755' },
          { label: 'Socha', value: '15757' },
          { label: 'Sogamoso', value: '15759' },
          { label: 'Somondoco', value: '15761' },
          { label: 'Sora', value: '15762' },
          { label: 'Sotaquirá', value: '15763' },
          { label: 'Soracá', value: '15764' },
          { label: 'Susacón', value: '15774' },
          { label: 'Sutamarchán', value: '15776' },
          { label: 'Sutatenza', value: '15778' },
          { label: 'Tasco', value: '15790' },
          { label: 'Tenza', value: '15798' },
          { label: 'Tibaná', value: '15804' },
          { label: 'Tibasosa', value: '15806' },
          { label: 'Tinjacá', value: '15808' },
          { label: 'Tipacoque', value: '15810' },
          { label: 'Toca', value: '15814' },
          { label: 'Togüí', value: '15816' },
          { label: 'Tópaga', value: '15820' },
          { label: 'Tota', value: '15822' },
          { label: 'Tununguá', value: '15832' },
          { label: 'Turmequé', value: '15835' },
          { label: 'Tuta', value: '15837' },
          { label: 'Tutazá', value: '15839' },
          { label: 'Úmbita', value: '15842' },
          { label: 'Ventaquemada', value: '15861' },
          { label: 'Viracachá', value: '15879' },
          { label: 'Zetaquira', value: '15897' },
        ],
      },
      {
        label: 'Caldas',
        value: '17',
        cities: [
          { label: 'Manizales', value: '17001' },
          { label: 'Aguadas', value: '17013' },
          { label: 'Anserma', value: '17042' },
          { label: 'Aranzazu', value: '17050' },
          { label: 'Belalcázar', value: '17088' },
          { label: 'Chinchiná', value: '17174' },
          { label: 'Filadelfia', value: '17272' },
          { label: 'La Dorada', value: '17380' },
          { label: 'La Merced', value: '17388' },
          { label: 'Manzanares', value: '17433' },
          { label: 'Marmato', value: '17442' },
          { label: 'Marquetalia', value: '17444' },
          { label: 'Marulanda', value: '17446' },
          { label: 'Neira', value: '17486' },
          { label: 'Norcasia', value: '17495' },
          { label: 'Pácora', value: '17513' },
          { label: 'Palestina', value: '17524' },
          { label: 'Pensilvania', value: '17541' },
          { label: 'Riosucio', value: '17614' },
          { label: 'Risaralda', value: '17616' },
          { label: 'Salamina', value: '17653' },
          { label: 'Samaná', value: '17662' },
          { label: 'San José', value: '17665' },
          { label: 'Supía', value: '17777' },
          { label: 'Victoria', value: '17867' },
          { label: 'Villamaría', value: '17873' },
          { label: 'Viterbo', value: '17877' },
        ],
      },
      {
        label: 'Caquetá',
        value: '18',
        cities: [
          { label: 'Florencia', value: '18001' },
          { label: 'Albania', value: '18029' },
          { label: 'Belén De Los Andaquíes', value: '18094' },
          { label: 'Cartagena Del Chairá', value: '18150' },
          { label: 'Curillo', value: '18205' },
          { label: 'El Doncello', value: '18247' },
          { label: 'El Paujíl', value: '18256' },
          { label: 'La Montañita', value: '18410' },
          { label: 'Milán', value: '18460' },
          { label: 'Morelia', value: '18479' },
          { label: 'Puerto Rico', value: '18592' },
          { label: 'San José Del Fragua', value: '18610' },
          { label: 'San Vicente Del Caguán', value: '18753' },
          { label: 'Solano', value: '18756' },
          { label: 'Solita', value: '18785' },
          { label: 'Valparaíso', value: '18860' },
        ],
      },
      {
        label: 'Cauca',
        value: '19',
        cities: [
          { label: 'Popayán', value: '19001' },
          { label: 'Almaguer', value: '19022' },
          { label: 'Argelia', value: '19050' },
          { label: 'Balboa', value: '19075' },
          { label: 'Bolívar', value: '19100' },
          { label: 'Buenos Aires', value: '19110' },
          { label: 'Cajibío', value: '19130' },
          { label: 'Caldono', value: '19137' },
          { label: 'Caloto', value: '19142' },
          { label: 'Corinto', value: '19212' },
          { label: 'El Tambo', value: '19256' },
          { label: 'Florencia', value: '19290' },
          { label: 'Guachené', value: '19300' },
          { label: 'Guapi', value: '19318' },
          { label: 'Inzá', value: '19355' },
          { label: 'Jambaló', value: '19364' },
          { label: 'La Sierra', value: '19392' },
          { label: 'La Vega', value: '19397' },
          { label: 'López De Micay', value: '19418' },
          { label: 'Mercaderes', value: '19450' },
          { label: 'Miranda', value: '19455' },
          { label: 'Morales', value: '19473' },
          { label: 'Padilla', value: '19513' },
          { label: 'Páez', value: '19517' },
          { label: 'Patía', value: '19532' },
          { label: 'Piamonte', value: '19533' },
          { label: 'Piendamó - Tunía', value: '19548' },
          { label: 'Puerto Tejada', value: '19573' },
          { label: 'Puracé', value: '19585' },
          { label: 'Rosas', value: '19622' },
          { label: 'San Sebastián', value: '19693' },
          { label: 'Santander De Quilichao', value: '19698' },
          { label: 'Santa Rosa', value: '19701' },
          { label: 'Silvia', value: '19743' },
          { label: 'Sotará - Paispamba', value: '19760' },
          { label: 'Suárez', value: '19780' },
          { label: 'Sucre', value: '19785' },
          { label: 'Timbío', value: '19807' },
          { label: 'Timbiquí', value: '19809' },
          { label: 'Toribío', value: '19821' },
          { label: 'Totoró', value: '19824' },
          { label: 'Villa Rica', value: '19845' },
        ],
      },
      {
        label: 'Cesar',
        value: '20',
        cities: [
          { label: 'Valledupar', value: '20001' },
          { label: 'Aguachica', value: '20011' },
          { label: 'Agustín Codazzi', value: '20013' },
          { label: 'Astrea', value: '20032' },
          { label: 'Becerril', value: '20045' },
          { label: 'Bosconia', value: '20060' },
          { label: 'Chimichagua', value: '20175' },
          { label: 'Chiriguaná', value: '20178' },
          { label: 'Curumaní', value: '20228' },
          { label: 'El Copey', value: '20238' },
          { label: 'El Paso', value: '20250' },
          { label: 'Gamarra', value: '20295' },
          { label: 'González', value: '20310' },
          { label: 'La Gloria', value: '20383' },
          { label: 'La Jagua De Ibirico', value: '20400' },
          { label: 'Manaure Balcón Del Cesar', value: '20443' },
          { label: 'Pailitas', value: '20517' },
          { label: 'Pelaya', value: '20550' },
          { label: 'Pueblo Bello', value: '20570' },
          { label: 'Río De Oro', value: '20614' },
          { label: 'La Paz', value: '20621' },
          { label: 'San Alberto', value: '20710' },
          { label: 'San Diego', value: '20750' },
          { label: 'San Martín', value: '20770' },
          { label: 'Tamalameque', value: '20787' },
        ],
      },
      {
        label: 'Córdoba',
        value: '23',
        cities: [
          { label: 'Montería', value: '23001' },
          { label: 'Ayapel', value: '23068' },
          { label: 'Buenavista', value: '23079' },
          { label: 'Canalete', value: '23090' },
          { label: 'Cereté', value: '23162' },
          { label: 'Chimá', value: '23168' },
          { label: 'Chinú', value: '23182' },
          { label: 'Ciénaga De Oro', value: '23189' },
          { label: 'Cotorra', value: '23300' },
          { label: 'La Apartada', value: '23350' },
          { label: 'Lorica', value: '23417' },
          { label: 'Los Córdobas', value: '23419' },
          { label: 'Momil', value: '23464' },
          { label: 'Montelíbano', value: '23466' },
          { label: 'Moñitos', value: '23500' },
          { label: 'Planeta Rica', value: '23555' },
          { label: 'Pueblo Nuevo', value: '23570' },
          { label: 'Puerto Escondido', value: '23574' },
          { label: 'Puerto Libertador', value: '23580' },
          { label: 'Purísima De La Concepción', value: '23586' },
          { label: 'Sahagún', value: '23660' },
          { label: 'San Andrés De Sotavento', value: '23670' },
          { label: 'San Antero', value: '23672' },
          { label: 'San Bernardo Del Viento', value: '23675' },
          { label: 'San Carlos', value: '23678' },
          { label: 'San José De Uré', value: '23682' },
          { label: 'San Pelayo', value: '23686' },
          { label: 'Tierralta', value: '23807' },
          { label: 'Tuchín', value: '23815' },
          { label: 'Valencia', value: '23855' },
        ],
      },
      {
        label: 'Cundinamarca',
        value: '25',
        cities: [
          { label: 'Agua De Dios', value: '25001' },
          { label: 'Albán', value: '25019' },
          { label: 'Anapoima', value: '25035' },
          { label: 'Anolaima', value: '25040' },
          { label: 'Arbeláez', value: '25053' },
          { label: 'Beltrán', value: '25086' },
          { label: 'Bituima', value: '25095' },
          { label: 'Bojacá', value: '25099' },
          { label: 'Cabrera', value: '25120' },
          { label: 'Cachipay', value: '25123' },
          { label: 'Cajicá', value: '25126' },
          { label: 'Caparrapí', value: '25148' },
          { label: 'Cáqueza', value: '25151' },
          { label: 'Carmen De Carupa', value: '25154' },
          { label: 'Chaguaní', value: '25168' },
          { label: 'Chía', value: '25175' },
          { label: 'Chipaque', value: '25178' },
          { label: 'Choachí', value: '25181' },
          { label: 'Chocontá', value: '25183' },
          { label: 'Cogua', value: '25200' },
          { label: 'Cota', value: '25214' },
          { label: 'Cucunubá', value: '25224' },
          { label: 'El Colegio', value: '25245' },
          { label: 'El Peñón', value: '25258' },
          { label: 'El Rosal', value: '25260' },
          { label: 'Facatativá', value: '25269' },
          { label: 'Fómeque', value: '25279' },
          { label: 'Fosca', value: '25281' },
          { label: 'Funza', value: '25286' },
          { label: 'Fúquene', value: '25288' },
          { label: 'Fusagasugá', value: '25290' },
          { label: 'Gachalá', value: '25293' },
          { label: 'Gachancipá', value: '25295' },
          { label: 'Gachetá', value: '25297' },
          { label: 'Gama', value: '25299' },
          { label: 'Girardot', value: '25307' },
          { label: 'Granada', value: '25312' },
          { label: 'Guachetá', value: '25317' },
          { label: 'Guaduas', value: '25320' },
          { label: 'Guasca', value: '25322' },
          { label: 'Guataquí', value: '25324' },
          { label: 'Guatavita', value: '25326' },
          { label: 'Guayabal De Síquima', value: '25328' },
          { label: 'Guayabetal', value: '25335' },
          { label: 'Gutiérrez', value: '25339' },
          { label: 'Jerusalén', value: '25368' },
          { label: 'Junín', value: '25372' },
          { label: 'La Calera', value: '25377' },
          { label: 'La Mesa', value: '25386' },
          { label: 'La Palma', value: '25394' },
          { label: 'La Peña', value: '25398' },
          { label: 'La Vega', value: '25402' },
          { label: 'Lenguazaque', value: '25407' },
          { label: 'Machetá', value: '25426' },
          { label: 'Madrid', value: '25430' },
          { label: 'Manta', value: '25436' },
          { label: 'Medina', value: '25438' },
          { label: 'Mosquera', value: '25473' },
          { label: 'Nariño', value: '25483' },
          { label: 'Nemocón', value: '25486' },
          { label: 'Nilo', value: '25488' },
          { label: 'Nimaima', value: '25489' },
          { label: 'Nocaima', value: '25491' },
          { label: 'Venecia', value: '25506' },
          { label: 'Pacho', value: '25513' },
          { label: 'Paime', value: '25518' },
          { label: 'Pandi', value: '25524' },
          { label: 'Paratebueno', value: '25530' },
          { label: 'Pasca', value: '25535' },
          { label: 'Puerto Salgar', value: '25572' },
          { label: 'Pulí', value: '25580' },
          { label: 'Quebradanegra', value: '25592' },
          { label: 'Quetame', value: '25594' },
          { label: 'Quipile', value: '25596' },
          { label: 'Apulo', value: '25599' },
          { label: 'Ricaurte', value: '25612' },
          { label: 'San Antonio Del Tequendama', value: '25645' },
          { label: 'San Bernardo', value: '25649' },
          { label: 'San Cayetano', value: '25653' },
          { label: 'San Francisco', value: '25658' },
          { label: 'San Juan De Rioseco', value: '25662' },
          { label: 'Sasaima', value: '25718' },
          { label: 'Sesquilé', value: '25736' },
          { label: 'Sibaté', value: '25740' },
          { label: 'Silvania', value: '25743' },
          { label: 'Simijaca', value: '25745' },
          { label: 'Soacha', value: '25754' },
          { label: 'Sopó', value: '25758' },
          { label: 'Subachoque', value: '25769' },
          { label: 'Suesca', value: '25772' },
          { label: 'Supatá', value: '25777' },
          { label: 'Susa', value: '25779' },
          { label: 'Sutatausa', value: '25781' },
          { label: 'Tabio', value: '25785' },
          { label: 'Tausa', value: '25793' },
          { label: 'Tena', value: '25797' },
          { label: 'Tenjo', value: '25799' },
          { label: 'Tibacuy', value: '25805' },
          { label: 'Tibirita', value: '25807' },
          { label: 'Tocaima', value: '25815' },
          { label: 'Tocancipá', value: '25817' },
          { label: 'Topaipí', value: '25823' },
          { label: 'Ubalá', value: '25839' },
          { label: 'Ubaque', value: '25841' },
          { label: 'Villa De San Diego De Ubaté', value: '25843' },
          { label: 'Une', value: '25845' },
          { label: 'Útica', value: '25851' },
          { label: 'Vergara', value: '25862' },
          { label: 'Vianí', value: '25867' },
          { label: 'Villagómez', value: '25871' },
          { label: 'Villapinzón', value: '25873' },
          { label: 'Villeta', value: '25875' },
          { label: 'Viotá', value: '25878' },
          { label: 'Yacopí', value: '25885' },
          { label: 'Zipacón', value: '25898' },
          { label: 'Zipaquirá', value: '25899' },
        ],
      },
      {
        label: 'Chocó',
        value: '27',
        cities: [
          { label: 'Quibdó', value: '27001' },
          { label: 'Acandí', value: '27006' },
          { label: 'Alto Baudó', value: '27025' },
          { label: 'Atrato', value: '27050' },
          { label: 'Bagadó', value: '27073' },
          { label: 'Bahía Solano', value: '27075' },
          { label: 'Bajo Baudó', value: '27077' },
          { label: 'Bojayá', value: '27099' },
          { label: 'El Cantón Del San Pablo', value: '27135' },
          { label: 'Carmen Del Darién', value: '27150' },
          { label: 'Cértegui', value: '27160' },
          { label: 'Condoto', value: '27205' },
          { label: 'El Carmen De Atrato', value: '27245' },
          { label: 'El Litoral Del San Juan', value: '27250' },
          { label: 'Istmina', value: '27361' },
          { label: 'Juradó', value: '27372' },
          { label: 'Lloró', value: '27413' },
          { label: 'Medio Atrato', value: '27425' },
          { label: 'Medio Baudó', value: '27430' },
          { label: 'Medio San Juan', value: '27450' },
          { label: 'Nóvita', value: '27491' },
          { label: 'Nuquí', value: '27495' },
          { label: 'Río Iró', value: '27580' },
          { label: 'Río Quito', value: '27600' },
          { label: 'Riosucio', value: '27615' },
          { label: 'San José Del Palmar', value: '27660' },
          { label: 'Sipí', value: '27745' },
          { label: 'Tadó', value: '27787' },
          { label: 'Unguía', value: '27800' },
          { label: 'Unión Panamericana', value: '27810' },
        ],
      },
      {
        label: 'Huila',
        value: '41',
        cities: [
          { label: 'Neiva', value: '41001' },
          { label: 'Acevedo', value: '41006' },
          { label: 'Agrado', value: '41013' },
          { label: 'Aipe', value: '41016' },
          { label: 'Algeciras', value: '41020' },
          { label: 'Altamira', value: '41026' },
          { label: 'Baraya', value: '41078' },
          { label: 'Campoalegre', value: '41132' },
          { label: 'Colombia', value: '41206' },
          { label: 'Elías', value: '41244' },
          { label: 'Garzón', value: '41298' },
          { label: 'Gigante', value: '41306' },
          { label: 'Guadalupe', value: '41319' },
          { label: 'Hobo', value: '41349' },
          { label: 'Íquira', value: '41357' },
          { label: 'Isnos', value: '41359' },
          { label: 'La Argentina', value: '41378' },
          { label: 'La Plata', value: '41396' },
          { label: 'Nátaga', value: '41483' },
          { label: 'Oporapa', value: '41503' },
          { label: 'Paicol', value: '41518' },
          { label: 'Palermo', value: '41524' },
          { label: 'Palestina', value: '41530' },
          { label: 'Pital', value: '41548' },
          { label: 'Pitalito', value: '41551' },
          { label: 'Rivera', value: '41615' },
          { label: 'Saladoblanco', value: '41660' },
          { label: 'San Agustín', value: '41668' },
          { label: 'Santa María', value: '41676' },
          { label: 'Suaza', value: '41770' },
          { label: 'Tarqui', value: '41791' },
          { label: 'Tesalia', value: '41797' },
          { label: 'Tello', value: '41799' },
          { label: 'Teruel', value: '41801' },
          { label: 'Timaná', value: '41807' },
          { label: 'Villavieja', value: '41872' },
          { label: 'Yaguará', value: '41885' },
        ],
      },
      {
        label: 'La Guajira',
        value: '44',
        cities: [
          { label: 'Riohacha', value: '44001' },
          { label: 'Albania', value: '44035' },
          { label: 'Barrancas', value: '44078' },
          { label: 'Dibulla', value: '44090' },
          { label: 'Distracción', value: '44098' },
          { label: 'El Molino', value: '44110' },
          { label: 'Fonseca', value: '44279' },
          { label: 'Hatonuevo', value: '44378' },
          { label: 'La Jagua Del Pilar', value: '44420' },
          { label: 'Maicao', value: '44430' },
          { label: 'Manaure', value: '44560' },
          { label: 'San Juan Del Cesar', value: '44650' },
          { label: 'Uribia', value: '44847' },
          { label: 'Urumita', value: '44855' },
          { label: 'Villanueva', value: '44874' },
        ],
      },
      {
        label: 'Magdalena',
        value: '47',
        cities: [
          { label: 'Santa Marta', value: '47001' },
          { label: 'Algarrobo', value: '47030' },
          { label: 'Aracataca', value: '47053' },
          { label: 'Ariguaní', value: '47058' },
          { label: 'Cerro De San Antonio', value: '47161' },
          { label: 'Chivolo', value: '47170' },
          { label: 'Ciénaga', value: '47189' },
          { label: 'Concordia', value: '47205' },
          { label: 'El Banco', value: '47245' },
          { label: 'El Piñón', value: '47258' },
          { label: 'El Retén', value: '47268' },
          { label: 'Fundación', value: '47288' },
          { label: 'Guamal', value: '47318' },
          { label: 'Nueva Granada', value: '47460' },
          { label: 'Pedraza', value: '47541' },
          { label: 'Pijiño Del Carmen', value: '47545' },
          { label: 'Pivijay', value: '47551' },
          { label: 'Plato', value: '47555' },
          { label: 'Puebloviejo', value: '47570' },
          { label: 'Remolino', value: '47605' },
          { label: 'Sabanas De San Ángel', value: '47660' },
          { label: 'Salamina', value: '47675' },
          { label: 'San Sebastián De Buenavista', value: '47692' },
          { label: 'San Zenón', value: '47703' },
          { label: 'Santa Ana', value: '47707' },
          { label: 'Santa Bárbara De Pinto', value: '47720' },
          { label: 'Sitionuevo', value: '47745' },
          { label: 'Tenerife', value: '47798' },
          { label: 'Zapayán', value: '47960' },
          { label: 'Zona Bananera', value: '47980' },
        ],
      },
      {
        label: 'Meta',
        value: '50',
        cities: [
          { label: 'Villavicencio', value: '50001' },
          { label: 'Acacías', value: '50006' },
          { label: 'Barranca De Upía', value: '50110' },
          { label: 'Cabuyaro', value: '50124' },
          { label: 'Castilla La Nueva', value: '50150' },
          { label: 'Cubarral', value: '50223' },
          { label: 'Cumaral', value: '50226' },
          { label: 'El Calvario', value: '50245' },
          { label: 'El Castillo', value: '50251' },
          { label: 'El Dorado', value: '50270' },
          { label: 'Fuente De Oro', value: '50287' },
          { label: 'Granada', value: '50313' },
          { label: 'Guamal', value: '50318' },
          { label: 'Mapiripán', value: '50325' },
          { label: 'Mesetas', value: '50330' },
          { label: 'La Macarena', value: '50350' },
          { label: 'Uribe', value: '50370' },
          { label: 'Lejanías', value: '50400' },
          { label: 'Puerto Concordia', value: '50450' },
          { label: 'Puerto Gaitán', value: '50568' },
          { label: 'Puerto López', value: '50573' },
          { label: 'Puerto Lleras', value: '50577' },
          { label: 'Puerto Rico', value: '50590' },
          { label: 'Restrepo', value: '50606' },
          { label: 'San Carlos De Guaroa', value: '50680' },
          { label: 'San Juan De Arama', value: '50683' },
          { label: 'San Juanito', value: '50686' },
          { label: 'San Martín', value: '50689' },
          { label: 'Vistahermosa', value: '50711' },
        ],
      },
      {
        label: 'Nariño',
        value: '52',
        cities: [
          { label: 'Pasto', value: '52001' },
          { label: 'Albán', value: '52019' },
          { label: 'Aldana', value: '52022' },
          { label: 'Ancuya', value: '52036' },
          { label: 'Arboleda', value: '52051' },
          { label: 'Barbacoas', value: '52079' },
          { label: 'Belén', value: '52083' },
          { label: 'Buesaco', value: '52110' },
          { label: 'Colón', value: '52203' },
          { label: 'Consacá', value: '52207' },
          { label: 'Contadero', value: '52210' },
          { label: 'Córdoba', value: '52215' },
          { label: 'Cuaspud Carlosama', value: '52224' },
          { label: 'Cumbal', value: '52227' },
          { label: 'Cumbitara', value: '52233' },
          { label: 'Chachagüí', value: '52240' },
          { label: 'El Charco', value: '52250' },
          { label: 'El Peñol', value: '52254' },
          { label: 'El Rosario', value: '52256' },
          { label: 'El Tablón De Gómez', value: '52258' },
          { label: 'El Tambo', value: '52260' },
          { label: 'Funes', value: '52287' },
          { label: 'Guachucal', value: '52317' },
          { label: 'Guaitarilla', value: '52320' },
          { label: 'Gualmatán', value: '52323' },
          { label: 'Iles', value: '52352' },
          { label: 'Imués', value: '52354' },
          { label: 'Ipiales', value: '52356' },
          { label: 'La Cruz', value: '52378' },
          { label: 'La Florida', value: '52381' },
          { label: 'La Llanada', value: '52385' },
          { label: 'La Tola', value: '52390' },
          { label: 'La Unión', value: '52399' },
          { label: 'Leiva', value: '52405' },
          { label: 'Linares', value: '52411' },
          { label: 'Los Andes', value: '52418' },
          { label: 'Magüí', value: '52427' },
          { label: 'Mallama', value: '52435' },
          { label: 'Mosquera', value: '52473' },
          { label: 'Nariño', value: '52480' },
          { label: 'Olaya Herrera', value: '52490' },
          { label: 'Ospina', value: '52506' },
          { label: 'Francisco Pizarro', value: '52520' },
          { label: 'Policarpa', value: '52540' },
          { label: 'Potosí', value: '52560' },
          { label: 'Providencia', value: '52565' },
          { label: 'Puerres', value: '52573' },
          { label: 'Pupiales', value: '52585' },
          { label: 'Ricaurte', value: '52612' },
          { label: 'Roberto Payán', value: '52621' },
          { label: 'Samaniego', value: '52678' },
          { label: 'Sandoná', value: '52683' },
          { label: 'San Bernardo', value: '52685' },
          { label: 'San Lorenzo', value: '52687' },
          { label: 'San Pablo', value: '52693' },
          { label: 'San Pedro De Cartago', value: '52694' },
          { label: 'Santa Bárbara', value: '52696' },
          { label: 'Santacruz', value: '52699' },
          { label: 'Sapuyes', value: '52720' },
          { label: 'Taminango', value: '52786' },
          { label: 'Tangua', value: '52788' },
          { label: 'San Andrés De Tumaco', value: '52835' },
          { label: 'Túquerres', value: '52838' },
          { label: 'Yacuanquer', value: '52885' },
        ],
      },
      {
        label: 'Norte De Santander',
        value: '54',
        cities: [
          { label: 'San José De Cúcuta', value: '54001' },
          { label: 'Ábrego', value: '54003' },
          { label: 'Arboledas', value: '54051' },
          { label: 'Bochalema', value: '54099' },
          { label: 'Bucarasica', value: '54109' },
          { label: 'Cácota', value: '54125' },
          { label: 'Cáchira', value: '54128' },
          { label: 'Chinácota', value: '54172' },
          { label: 'Chitagá', value: '54174' },
          { label: 'Convención', value: '54206' },
          { label: 'Cucutilla', value: '54223' },
          { label: 'Durania', value: '54239' },
          { label: 'El Carmen', value: '54245' },
          { label: 'El Tarra', value: '54250' },
          { label: 'El Zulia', value: '54261' },
          { label: 'Gramalote', value: '54313' },
          { label: 'Hacarí', value: '54344' },
          { label: 'Herrán', value: '54347' },
          { label: 'Labateca', value: '54377' },
          { label: 'La Esperanza', value: '54385' },
          { label: 'La Playa', value: '54398' },
          { label: 'Los Patios', value: '54405' },
          { label: 'Lourdes', value: '54418' },
          { label: 'Mutiscua', value: '54480' },
          { label: 'Ocaña', value: '54498' },
          { label: 'Pamplona', value: '54518' },
          { label: 'Pamplonita', value: '54520' },
          { label: 'Puerto Santander', value: '54553' },
          { label: 'Ragonvalia', value: '54599' },
          { label: 'Salazar', value: '54660' },
          { label: 'San Calixto', value: '54670' },
          { label: 'San Cayetano', value: '54673' },
          { label: 'Santiago', value: '54680' },
          { label: 'Sardinata', value: '54720' },
          { label: 'Silos', value: '54743' },
          { label: 'Teorama', value: '54800' },
          { label: 'Tibú', value: '54810' },
          { label: 'Toledo', value: '54820' },
          { label: 'Villa Caro', value: '54871' },
          { label: 'Villa Del Rosario', value: '54874' },
        ],
      },
      {
        label: 'Quindío',
        value: '63',
        cities: [
          { label: 'Armenia', value: '63001' },
          { label: 'Buenavista', value: '63111' },
          { label: 'Calarcá', value: '63130' },
          { label: 'Circasia', value: '63190' },
          { label: 'Córdoba', value: '63212' },
          { label: 'Filandia', value: '63272' },
          { label: 'Génova', value: '63302' },
          { label: 'La Tebaida', value: '63401' },
          { label: 'Montenegro', value: '63470' },
          { label: 'Pijao', value: '63548' },
          { label: 'Quimbaya', value: '63594' },
          { label: 'Salento', value: '63690' },
        ],
      },
      {
        label: 'Risaralda',
        value: '66',
        cities: [
          { label: 'Pereira', value: '66001' },
          { label: 'Apía', value: '66045' },
          { label: 'Balboa', value: '66075' },
          { label: 'Belén De Umbría', value: '66088' },
          { label: 'Dosquebradas', value: '66170' },
          { label: 'Guática', value: '66318' },
          { label: 'La Celia', value: '66383' },
          { label: 'La Virginia', value: '66400' },
          { label: 'Marsella', value: '66440' },
          { label: 'Mistrató', value: '66456' },
          { label: 'Pueblo Rico', value: '66572' },
          { label: 'Quinchía', value: '66594' },
          { label: 'Santa Rosa De Cabal', value: '66682' },
          { label: 'Santuario', value: '66687' },
        ],
      },
      {
        label: 'Santander',
        value: '68',
        cities: [
          { label: 'Bucaramanga', value: '68001' },
          { label: 'Aguada', value: '68013' },
          { label: 'Albania', value: '68020' },
          { label: 'Aratoca', value: '68051' },
          { label: 'Barbosa', value: '68077' },
          { label: 'Barichara', value: '68079' },
          { label: 'Barrancabermeja', value: '68081' },
          { label: 'Betulia', value: '68092' },
          { label: 'Bolívar', value: '68101' },
          { label: 'Cabrera', value: '68121' },
          { label: 'California', value: '68132' },
          { label: 'Capitanejo', value: '68147' },
          { label: 'Carcasí', value: '68152' },
          { label: 'Cepitá', value: '68160' },
          { label: 'Cerrito', value: '68162' },
          { label: 'Charalá', value: '68167' },
          { label: 'Charta', value: '68169' },
          { label: 'Chima', value: '68176' },
          { label: 'Chipatá', value: '68179' },
          { label: 'Cimitarra', value: '68190' },
          { label: 'Concepción', value: '68207' },
          { label: 'Confines', value: '68209' },
          { label: 'Contratación', value: '68211' },
          { label: 'Coromoro', value: '68217' },
          { label: 'Curití', value: '68229' },
          { label: 'El Carmen De Chucurí', value: '68235' },
          { label: 'El Guacamayo', value: '68245' },
          { label: 'El Peñón', value: '68250' },
          { label: 'El Playón', value: '68255' },
          { label: 'Encino', value: '68264' },
          { label: 'Enciso', value: '68266' },
          { label: 'Florián', value: '68271' },
          { label: 'Floridablanca', value: '68276' },
          { label: 'Galán', value: '68296' },
          { label: 'Gámbita', value: '68298' },
          { label: 'Girón', value: '68307' },
          { label: 'Guaca', value: '68318' },
          { label: 'Guadalupe', value: '68320' },
          { label: 'Guapotá', value: '68322' },
          { label: 'Guavatá', value: '68324' },
          { label: 'Güepsa', value: '68327' },
          { label: 'Hato', value: '68344' },
          { label: 'Jesús María', value: '68368' },
          { label: 'Jordán', value: '68370' },
          { label: 'La Belleza', value: '68377' },
          { label: 'Landázuri', value: '68385' },
          { label: 'La Paz', value: '68397' },
          { label: 'Lebrija', value: '68406' },
          { label: 'Los Santos', value: '68418' },
          { label: 'Macaravita', value: '68425' },
          { label: 'Málaga', value: '68432' },
          { label: 'Matanza', value: '68444' },
          { label: 'Mogotes', value: '68464' },
          { label: 'Molagavita', value: '68468' },
          { label: 'Ocamonte', value: '68498' },
          { label: 'Oiba', value: '68500' },
          { label: 'Onzaga', value: '68502' },
          { label: 'Palmar', value: '68522' },
          { label: 'Palmas Del Socorro', value: '68524' },
          { label: 'Páramo', value: '68533' },
          { label: 'Piedecuesta', value: '68547' },
          { label: 'Pinchote', value: '68549' },
          { label: 'Puente Nacional', value: '68572' },
          { label: 'Puerto Parra', value: '68573' },
          { label: 'Puerto Wilches', value: '68575' },
          { label: 'Rionegro', value: '68615' },
          { label: 'Sabana De Torres', value: '68655' },
          { label: 'San Andrés', value: '68669' },
          { label: 'San Benito', value: '68673' },
          { label: 'San Gil', value: '68679' },
          { label: 'San Joaquín', value: '68682' },
          { label: 'San José De Miranda', value: '68684' },
          { label: 'San Miguel', value: '68686' },
          { label: 'San Vicente De Chucurí', value: '68689' },
          { label: 'Santa Bárbara', value: '68705' },
          { label: 'Santa Helena Del Opón', value: '68720' },
          { label: 'Simacota', value: '68745' },
          { label: 'Socorro', value: '68755' },
          { label: 'Suaita', value: '68770' },
          { label: 'Sucre', value: '68773' },
          { label: 'Suratá', value: '68780' },
          { label: 'Tona', value: '68820' },
          { label: 'Valle De San José', value: '68855' },
          { label: 'Vélez', value: '68861' },
          { label: 'Vetas', value: '68867' },
          { label: 'Villanueva', value: '68872' },
          { label: 'Zapatoca', value: '68895' },
        ],
      },
      {
        label: 'Sucre',
        value: '70',
        cities: [
          { label: 'Sincelejo', value: '70001' },
          { label: 'Buenavista', value: '70110' },
          { label: 'Caimito', value: '70124' },
          { label: 'Colosó', value: '70204' },
          { label: 'Corozal', value: '70215' },
          { label: 'Coveñas', value: '70221' },
          { label: 'Chalán', value: '70230' },
          { label: 'El Roble', value: '70233' },
          { label: 'Galeras', value: '70235' },
          { label: 'Guaranda', value: '70265' },
          { label: 'La Unión', value: '70400' },
          { label: 'Los Palmitos', value: '70418' },
          { label: 'Majagual', value: '70429' },
          { label: 'Morroa', value: '70473' },
          { label: 'Ovejas', value: '70508' },
          { label: 'Palmito', value: '70523' },
          { label: 'Sampués', value: '70670' },
          { label: 'San Benito Abad', value: '70678' },
          { label: 'San Juan De Betulia', value: '70702' },
          { label: 'San Marcos', value: '70708' },
          { label: 'San Onofre', value: '70713' },
          { label: 'San Pedro', value: '70717' },
          { label: 'San Luis De Sincé', value: '70742' },
          { label: 'Sucre', value: '70771' },
          { label: 'Santiago De Tolú', value: '70820' },
          { label: 'San José De Toluviejo', value: '70823' },
        ],
      },
      {
        label: 'Tolima',
        value: '73',
        cities: [
          { label: 'Ibagué', value: '73001' },
          { label: 'Alpujarra', value: '73024' },
          { label: 'Alvarado', value: '73026' },
          { label: 'Ambalema', value: '73030' },
          { label: 'Anzoátegui', value: '73043' },
          { label: 'Armero', value: '73055' },
          { label: 'Ataco', value: '73067' },
          { label: 'Cajamarca', value: '73124' },
          { label: 'Carmen De Apicalá', value: '73148' },
          { label: 'Casabianca', value: '73152' },
          { label: 'Chaparral', value: '73168' },
          { label: 'Coello', value: '73200' },
          { label: 'Coyaima', value: '73217' },
          { label: 'Cunday', value: '73226' },
          { label: 'Dolores', value: '73236' },
          { label: 'Espinal', value: '73268' },
          { label: 'Falan', value: '73270' },
          { label: 'Flandes', value: '73275' },
          { label: 'Fresno', value: '73283' },
          { label: 'Guamo', value: '73319' },
          { label: 'Herveo', value: '73347' },
          { label: 'Honda', value: '73349' },
          { label: 'Icononzo', value: '73352' },
          { label: 'Lérida', value: '73408' },
          { label: 'Líbano', value: '73411' },
          { label: 'San Sebastián De Mariquita', value: '73443' },
          { label: 'Melgar', value: '73449' },
          { label: 'Murillo', value: '73461' },
          { label: 'Natagaima', value: '73483' },
          { label: 'Ortega', value: '73504' },
          { label: 'Palocabildo', value: '73520' },
          { label: 'Piedras', value: '73547' },
          { label: 'Planadas', value: '73555' },
          { label: 'Prado', value: '73563' },
          { label: 'Purificación', value: '73585' },
          { label: 'Rioblanco', value: '73616' },
          { label: 'Roncesvalles', value: '73622' },
          { label: 'Rovira', value: '73624' },
          { label: 'Saldaña', value: '73671' },
          { label: 'San Antonio', value: '73675' },
          { label: 'San Luis', value: '73678' },
          { label: 'Santa Isabel', value: '73686' },
          { label: 'Suárez', value: '73770' },
          { label: 'Valle De San Juan', value: '73854' },
          { label: 'Venadillo', value: '73861' },
          { label: 'Villahermosa', value: '73870' },
          { label: 'Villarrica', value: '73873' },
        ],
      },
      {
        label: 'Valle Del Cauca',
        value: '76',
        cities: [
          { label: 'Cali', value: '76001' },
          { label: 'Alcalá', value: '76020' },
          { label: 'Andalucía', value: '76036' },
          { label: 'Ansermanuevo', value: '76041' },
          { label: 'Argelia', value: '76054' },
          { label: 'Bolívar', value: '76100' },
          { label: 'Buenaventura', value: '76109' },
          { label: 'Guadalajara De Buga', value: '76111' },
          { label: 'Bugalagrande', value: '76113' },
          { label: 'Caicedonia', value: '76122' },
          { label: 'Calima', value: '76126' },
          { label: 'Candelaria', value: '76130' },
          { label: 'Cartago', value: '76147' },
          { label: 'Dagua', value: '76233' },
          { label: 'El Águila', value: '76243' },
          { label: 'El Cairo', value: '76246' },
          { label: 'El Cerrito', value: '76248' },
          { label: 'El Dovio', value: '76250' },
          { label: 'Florida', value: '76275' },
          { label: 'Ginebra', value: '76306' },
          { label: 'Guacarí', value: '76318' },
          { label: 'Jamundí', value: '76364' },
          { label: 'La Cumbre', value: '76377' },
          { label: 'La Unión', value: '76400' },
          { label: 'La Victoria', value: '76403' },
          { label: 'Obando', value: '76497' },
          { label: 'Palmira', value: '76520' },
          { label: 'Pradera', value: '76563' },
          { label: 'Restrepo', value: '76606' },
          { label: 'Riofrío', value: '76616' },
          { label: 'Roldanillo', value: '76622' },
          { label: 'San Pedro', value: '76670' },
          { label: 'Sevilla', value: '76736' },
          { label: 'Toro', value: '76823' },
          { label: 'Trujillo', value: '76828' },
          { label: 'Tuluá', value: '76834' },
          { label: 'Ulloa', value: '76845' },
          { label: 'Versalles', value: '76863' },
          { label: 'Vijes', value: '76869' },
          { label: 'Yotoco', value: '76890' },
          { label: 'Yumbo', value: '76892' },
          { label: 'Zarzal', value: '76895' },
        ],
      },
      {
        label: 'Arauca',
        value: '81',
        cities: [
          { label: 'Arauca', value: '81001' },
          { label: 'Arauquita', value: '81065' },
          { label: 'Cravo Norte', value: '81220' },
          { label: 'Fortul', value: '81300' },
          { label: 'Puerto Rondón', value: '81591' },
          { label: 'Saravena', value: '81736' },
          { label: 'Tame', value: '81794' },
        ],
      },
      {
        label: 'Casanare',
        value: '85',
        cities: [
          { label: 'Yopal', value: '85001' },
          { label: 'Aguazul', value: '85010' },
          { label: 'Chámeza', value: '85015' },
          { label: 'Hato Corozal', value: '85125' },
          { label: 'La Salina', value: '85136' },
          { label: 'Maní', value: '85139' },
          { label: 'Monterrey', value: '85162' },
          { label: 'Nunchía', value: '85225' },
          { label: 'Orocué', value: '85230' },
          { label: 'Paz De Ariporo', value: '85250' },
          { label: 'Pore', value: '85263' },
          { label: 'Recetor', value: '85279' },
          { label: 'Sabanalarga', value: '85300' },
          { label: 'Sácama', value: '85315' },
          { label: 'San Luis De Palenque', value: '85325' },
          { label: 'Támara', value: '85400' },
          { label: 'Tauramena', value: '85410' },
          { label: 'Trinidad', value: '85430' },
          { label: 'Villanueva', value: '85440' },
        ],
      },
      {
        label: 'Putumayo',
        value: '86',
        cities: [
          { label: 'Mocoa', value: '86001' },
          { label: 'Colón', value: '86219' },
          { label: 'Orito', value: '86320' },
          { label: 'Puerto Asís', value: '86568' },
          { label: 'Puerto Caicedo', value: '86569' },
          { label: 'Puerto Guzmán', value: '86571' },
          { label: 'Puerto Leguízamo', value: '86573' },
          { label: 'Sibundoy', value: '86749' },
          { label: 'San Francisco', value: '86755' },
          { label: 'San Miguel', value: '86757' },
          { label: 'Santiago', value: '86760' },
          { label: 'Valle Del Guamuez', value: '86865' },
          { label: 'Villagarzón', value: '86885' },
        ],
      },
      {
        label: 'Archipiélago De San Andrés, Providencia Y Santa Catalina',
        value: '88',
        cities: [
          { label: 'San Andrés', value: '88001' },
          { label: 'Providencia', value: '88564' },
        ],
      },
      {
        label: 'Amazonas',
        value: '91',
        cities: [
          { label: 'Leticia', value: '91001' },
          { label: 'El Encanto', value: '91263' },
          { label: 'La Chorrera', value: '91405' },
          { label: 'La Pedrera', value: '91407' },
          { label: 'La Victoria', value: '91430' },
          { label: 'Mirití - Paraná', value: '91460' },
          { label: 'Puerto Alegría', value: '91530' },
          { label: 'Puerto Arica', value: '91536' },
          { label: 'Puerto Nariño', value: '91540' },
          { label: 'Puerto Santander', value: '91669' },
          { label: 'Tarapacá', value: '91798' },
        ],
      },
      {
        label: 'Guainía',
        value: '94',
        cities: [
          { label: 'Inírida', value: '94001' },
          { label: 'Barrancominas', value: '94343' },
          { label: 'San Felipe', value: '94883' },
          { label: 'Puerto Colombia', value: '94884' },
          { label: 'La Guadalupe', value: '94885' },
          { label: 'Cacahual', value: '94886' },
          { label: 'Pana Pana', value: '94887' },
          { label: 'Morichal', value: '94888' },
        ],
      },
      {
        label: 'Guaviare',
        value: '95',
        cities: [
          { label: 'San José Del Guaviare', value: '95001' },
          { label: 'Calamar', value: '95015' },
          { label: 'El Retorno', value: '95025' },
          { label: 'Miraflores', value: '95200' },
        ],
      },
      {
        label: 'Vaupés',
        value: '97',
        cities: [
          { label: 'Mitú', value: '97001' },
          { label: 'Carurú', value: '97161' },
          { label: 'Pacoa', value: '97511' },
          { label: 'Taraira', value: '97666' },
          { label: 'Papunahua', value: '97777' },
          { label: 'Yavaraté', value: '97889' },
        ],
      },
      {
        label: 'Vichada',
        value: '99',
        cities: [
          { label: 'Puerto Carreño', value: '99001' },
          { label: 'La Primavera', value: '99524' },
          { label: 'Santa Rosalía', value: '99624' },
          { label: 'Cumaribo', value: '99773' },
        ],
      },
    ],
  },
  {
    label: 'Argentina',
    value: 'AR',
    states: [
      {
        label: 'Buenos Aires',
        value: 'BA',
        cities: [{ label: 'BsAs', value: 'BsAs', districts: [] }],
      },
      {
        label: 'Córdoba',
        value: 'CB',
        cities: [{ label: 'Córdoba', value: 'cb', districts: [] }],
      },
      {
        label: 'Salta',
        value: 'SA',
        cities: [{ label: 'Salta', value: 'ST', districts: [] }],
      },
      {
        label: 'Entre ríos',
        value: 'ER',
        cities: [{ label: 'Paraná', value: 'PN', districts: [] }],
      },
      {
        label: 'Santa Cruz',
        value: 'SC',
        cities: [{ label: 'Río Gallegos', value: 'Río Gallegos', districts: [] }],
      },
    ],
  },
  {
    label: 'México',
    value: 'MX',
    states: [
      {
        label: 'Ciudad de México',
        value: 'CDMX',
        cities: [{ label: 'CDMX', value: 'CDMX', districts: [] }],
      },
      {
        label: 'Morelos',
        value: 'MO',
        cities: [
          { label: 'Cuernavaca', value: 'CV', districts: [] },
          { label: 'Miacatlán', value: 'MT', districts: [] },
        ],
      },
      {
        label: 'Chiapas',
        value: 'CS',
        cities: [{ label: 'Tuxla Gutiérrez', value: 'TG', districts: [] }],
      },
      {
        label: 'Oaxaca',
        value: 'OA',
        cities: [{ label: 'Oaxaca de Juárez', value: 'OX', districts: [] }],
      },
      {
        label: 'Puebla',
        value: 'PU',
        cities: [{ label: 'Puebla de Zaragoza', value: 'PZG', districts: [] }],
      },
    ],
  },
  {
    label: 'Perú',
    value: 'PE',
    states: [
      {
        label: 'Arequipa',
        value: 'Arequipa',
        cities: [{ label: 'Arequipa', value: 'Arequipa', districts: [] }],
      },
      {
        label: 'Cuzco',
        value: 'Cuzco',
        cities: [{ label: 'Cuzco', value: 'Cuzco', districts: [] }],
      },
      {
        label: 'Ica',
        value: 'ICA',
        cities: [{ label: 'Ica', value: 'Ica', districts: [] }],
      },
      {
        label: 'Lima Metropolitana',
        value: 'Lima',
        cities: [{ label: 'Lima', value: 'Lima', districts: [] }],
      },
      {
        label: 'Loreto',
        value: 'Lo',
        cities: [{ label: 'Iquitos', value: 'IQ', districts: [] }],
      },
    ],
  },
];

export const createCitySelect = (citySelectorParams: CitySelectorParams) => {
  const { fieldData, handlers } = citySelectorParams;
  const { componentParams } = fieldData || {};
  let { highSelectionLevel, minimumSelectionLevel } = componentParams || {};
  const { register, formState } = useFormContext();
  const dispatch = useDispatch();

  const { actions: countryActions } = useCountriesSlice();

  const [countryOptions, updateCountryOptions] = useState(countries);

  const availableCountries = useSelector(selectorCountries.selectItems);

  const [selectedCountry, updateSelectedCountry] = useState();
  const [stateOptions, updateStateOptions] = useState([]);
  const [selectedState, updateSelectedState] = useState();
  const [cityOptions, updateCityOptions] = useState([]);
  const [selectedCity, updateSelectedCity] = useState();
  const [districtOptions, updateDistrictOptions] = useState([]);
  const [selectedDistrict, updateSelectedDistrict] = useState();

  if (!highSelectionLevel) {
    highSelectionLevel = CitySelectionLevel.COUNTRY;
  }

  if (!minimumSelectionLevel) {
    minimumSelectionLevel = CitySelectionLevel.CITY;
  }

  useEffect(() => {
    dispatch(countryActions.loadItems({}));
  }, []);

  const customHandlers = {
    onChangecountry: (data: any) => {
      // updateSelectedCountry(data.value);
      // updateStateOptions(countries.find((country: any) => country.value === data.value).states);
    },
    onChangestate: (data: any) => {
      if (selectedCountry) {
        updateSelectedState(data.value);
        updateCityOptions(
          countries
            .find((country: any) => country.value === selectedCountry)
            .states?.find((state: any) => state.value === data.value).cities
        );
      }
    },
    onChangecity: (data: any) => {
      if (selectedCountry && selectedState) {
        updateSelectedCity(data.value);
        updateDistrictOptions(
          countries
            .find((country: any) => country.value === selectedCountry)
            .states?.find((state: any) => state.value === selectedState)
            .cities?.find((city: any) => city.value === data.value).districts
        );
      }
    },
  };
  const { translateText } = useI18n();

  const fieldDataCountries: DynamicFieldData = {
    label: translateText(`app.global_dictionary.location.country`),
    fieldName: 'country',
    inputType: 'select',
    options: availableCountries
      .map((country) => {
        return {
          label: `${country.name}${country.name !== country.native ? ' (' + country.native + ')' : ''}`,
          value: `${country.identifier}`,
        };
      })
      .sort((a, b) => a.label.localeCompare(b.label)),
  };
  if (selectedCountry) {
    fieldDataCountries.defaultValue = selectedCountry;
  }
  const fieldDataStates: DynamicFieldData = {
    label: translateText(`app.global_dictionary.location.state`),
    fieldName: 'state',
    inputType: 'select',
    options: stateOptions,
  };
  const fieldDataCities: DynamicFieldData = {
    label: translateText(`app.global_dictionary.location.city`),
    fieldName: 'city',
    inputType: 'select',
    options: cityOptions,
  };
  const fieldDataDistricts: DynamicFieldData = {
    label: translateText(`app.global_dictionary.location.district`),
    fieldName: 'district',
    inputType: 'select',
    options: districtOptions,
  };

  return (
    <div>
      <FormLabel>{fieldData.label}</FormLabel>
      {minimumSelectionLevel <= CitySelectionLevel.COUNTRY &&
        CitySelectionLevel.COUNTRY <= highSelectionLevel &&
        createSelect({
          fieldData: fieldDataCountries,
          handlers: customHandlers,
        })}
      {minimumSelectionLevel <= CitySelectionLevel.STATE &&
        CitySelectionLevel.STATE <= highSelectionLevel &&
        createSelect({
          fieldData: fieldDataStates,
          handlers: customHandlers,
        })}
      {minimumSelectionLevel <= CitySelectionLevel.CITY &&
        CitySelectionLevel.CITY <= highSelectionLevel &&
        createSelect({
          fieldData: fieldDataCities,
          handlers: customHandlers,
        })}
      {minimumSelectionLevel <= CitySelectionLevel.DISTRICT &&
        CitySelectionLevel.DISTRICT <= highSelectionLevel &&
        createSelect({
          fieldData: fieldDataDistricts,
          handlers: customHandlers,
        })}
    </div>
  );
};
