export enum UserNameAvailabilityStatus{
  AVAILABLE,
  IDENTIFIED,
  TAKEN,
}

export enum AppErrorCodes {
  // Errores de Autenticación y Autorización
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_NO_USER_PROVIDED = 'AUTH_NO_USER_PROVIDED',
  AUTH_NO_PASSWORD_PROVIDED = 'AUTH_NO_PASSWORD_PROVIDED',
  AUTH_NO_TOKEN_PROVIDED = 'AUTH_NO_TOKEN_PROVIDED',
  AUTH_WRONG_PASSWORD = 'AUTH_WRONG_PASSWORD',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_PERMISSION_DENIED = 'AUTH_PERMISSION_DENIED',

  // Errores de Red
  NETWORK_ERROR = 'NETWORK_ERROR',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  NETWORK_NOT_CONNECTED = 'NETWORK_NOT_CONNECTED',

  // Errores de Validación
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_WEAK = 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_FIELD_REQUIRED = 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_USERNAME_TAKEN = 'VALIDATION_USERNAME_TAKEN',

  // Errores de Usuario
  USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
  USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED',
  USER_ACCOUNT_SUSPENDED = 'USER_ACCOUNT_SUSPENDED',
  USER_ACCOUNT_DELETED = 'USER_ACCOUNT_DELETED',

  // Errores de Contenido
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  CONTENT_UPLOAD_FAILED = 'CONTENT_UPLOAD_FAILED',
  CONTENT_TOO_LARGE = 'CONTENT_TOO_LARGE',
  CONTENT_TYPE_NOT_SUPPORTED = 'CONTENT_TYPE_NOT_SUPPORTED',

  // Errores de Amistad/Conexión
  CONNECTION_REQUEST_FAILED = 'CONNECTION_REQUEST_FAILED',
  CONNECTION_ALREADY_EXISTS = 'CONNECTION_ALREADY_EXISTS',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',

  // Errores de Mensajes
  MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_CONTENT_INVALID = 'MESSAGE_CONTENT_INVALID',

  // Errores de Publicación
  POST_CREATE_FAILED = 'POST_CREATE_FAILED',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_UPDATE_FAILED = 'POST_UPDATE_FAILED',
  POST_DELETE_FAILED = 'POST_DELETE_FAILED',

  // Errores de Pago
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID',
  PAYMENT_INSUFFICIENT_FUNDS = 'PAYMENT_INSUFFICIENT_FUNDS',

  // Errores del Servidor
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_MAINTENANCE = 'SERVER_MAINTENANCE',

  // Errores Desconocidos
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
