export enum PATHS {
  HOME = 'home',
  SIGN_UP = 'signup',
  LOGIN = 'login',
  CONTACT_US = 'contact',
  PRIVACY_POLICY = 'privacy',
  TERMS_OF_SERVICE = 'terms',
  PLANS = 'plans',
  ACADEMIES = 'academies',
  ARTISTS = 'artists',
  CULTURAL_AGENDA = 'agenda',
  MAIN = '',
  EVENTS = 'events',
  CALENDAR = 'calendar',
  PREBOOKING_REQUESTS_LIST = 'prebookings',
  BUSINESS = 'business',
  USERNAME = '@',
  NOT_FOUND = '',
  SHOWS = 'shows',
  INDUSTRY_OFFER = 'offer',
  INDUSTRY = 'industry',
  OPPORTUNITIES = 'opportunities',
  PROFILE = 'profile',
  PLACES = 'places',
  PROMOTERS = 'promoters',
  RIDERS = 'riders',
  SEARCH = 'search',
  BASENAME = 'artistsHive',
  SETTINGS = 'settings',
  MY_FAVOURITES = 'favourites',
  STAGE_PLOT = 'stagePlot',
  TOURS_OUTLINE = 'toursOutline',
  FAQ = 'faq',
  PAYMENTS = 'payment',
  OPEN_CALLS = 'open-calls',
  CC = 'cc',
  CIRCUITO_HIVE_2026 = 'circuito-hive-2026',
  REDIRECT_UNAUTHORIZED_AND_UNLOGGED_USER = '/home',
  REDIRECT_UNAUTHORIZED_AND_LOGGED_USER = '/home',
}

export enum SUB_PATHS {
  CONFIRMATION = 'confirmation',
  CREATE = 'new',
  EDIT = 'edit',
  EDITOR = 'editor',
  ELEMENT_DETAILS = 'details',
  AGENDA = 'agenda',
  APPLY = 'apply',
}

export enum URL_PARAMETER_NAMES {
  ELEMENT_ID = 'id',
  NEXT = 'next',
  ROLE = 'role',
}
